### ISSUE TITLE
How to improve SvgUri rendering for multiple elements

### ISSUE THREAD

**Issue by lcsvcn** [react-native-community/react-native-svg#1163]
How can I cache or maybe improve multiple SvgUri elements load time?

I can't use resource svg or other options because does not fit my purpose or does not work for both devices!

More info can be found on my question on StackOverflow:
https://stackoverflow.com/questions/58489873/how-to-improve-svguri-rendering-for-multiple-elements

**Comment by msand** [comment]
You can implement a custom SvgUri component with a cache, e.g. using a [WeakMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) from uri to the jsx output from parse, or alternatively, three WeakMaps, one from uri to promises (from calling fetch with the uri), another from uri to svg / xml strings, and another from either uri or from svg / xml to jsx output from parse. 

You also need to handle race-conditions / multiple simultaneous requests efficiently, such that if it's already requested, it won't make another request, but chain another then handler onto the existing one instead, and handle that the content is only parsed/converted to jsx once, even if requested by several.

So, use WeakMaps to ensure that any uri is only fetched once, the same xml string is only parsed once, and only converted to jsx once.

But, in this case if I were you, I would also look into using the svg marker element, to render a single svg canvas with all your markers at once, instead of creating a canvas for each marker. Especially if you're rendering the same marker several times.

**Comment by msand** [comment]
https://github.com/react-native-community/react-native-svg#marker
