### ISSUE TITLE
Image : RN Upgrade (replaced deprecated bridge.imageLoader calls with moduleForClass API)

### ISSUE THREAD

**Issue by PalsRoy** [react-native-community/react-native-svg#1198]
**Bug**
After upgrading to RN 61.3 the svgs which contain "Image" tag show the below warning. 

**Environment info**
"react-native": "0.61.3"
"react-native-svg-transformer": "0.12.1"

**Output**
Calling bridge.imageLoader is deprecated and will not work in newer versions of RN. Please update to the moduleForClass API or turboModuleLookupDelegate API.

**Similar Observations elsewhere**
There has been a similar issue reported on react-native-maps and the resolution is here [#3125](https://github.com/react-native-community/react-native-maps/pull/3125)

**Comment by msand** [comment]
I think this is fixed in v9.12.0 and newer: https://github.com/react-native-community/react-native-svg/releases/tag/v9.12.0
https://github.com/react-native-community/react-native-svg/commit/5452144468c2fbc157db7383e00ebd72bdad6af0
https://github.com/react-native-community/react-native-svg/commit/3c22c9757277145a18a509c3aee36dddc6a610e7
