### ISSUE TITLE
Parse svg files

### ISSUE THREAD

**Issue by normanrz** [react-native-community/react-native-svg#12]
I have a bunch of SVG files that I'd like to render in my app. Is there a way to render them with this module? I could imagine a parser that outputs a React render tree.

**Comment by pietgk** [comment]
I could not find a tool that does this.
Currently i use paintcode to simplify the svg context a bit and then manual labor.
please not that some defaults in svg need explicit values in react-native-svg.

The advantage is f.e. that you can use javascript property values to make the svg more controllable.

**Comment by caledhwa** [comment]
I'm wondering if we could simply creat a JS tool to do parsing and reformatting of the SVG standard and then set up the proper JSX... Such as the x/y from transform(), etc

**Comment by caledhwa** [comment]
Suggestion! This library seems pretty clean for parsing transform... https://github.com/nidu/svg-transform-parser - we could integrate the regular transform into react-native-svg which will bring us one step closer to compatibility with standard SVG format. I still think we have a fairly large issue with RN components being Proper cased, however, not having to re-format my SVG stuff in regards to all of the transform attributes could be a big bonus. Maybe I'll see if I can fire a PR integrating this (with of course backward compatibility), it could add value. Thoughts?

**Comment by jonlay** [comment]
Not an ideal solution (sometimes you don't want to upload SVGs as an icon font), but if anyone else stumbles across this thread and is looking to display a set of SVG icons in React Native, try https://github.com/oblador/react-native-vector-icons

You can upload all your icons as a custom set to IcoMoon, then use them as an icon font in your app.

**Comment by matc4** [comment]
Hello, i made this library [react-native-svg-uri](https://github.com/matc4/react-native-svg-uri).
You can render SVG Images from an URL or a static file.

**Comment by 7ynk3r** [comment]
that looks handy! thanks @matc4 

i'm thinking that we could do an integration with react-native directly give that https://github.com/facebook/react-native/tree/master/Libraries/ART ;)

**Comment by matc4** [comment]
Hi @7ynk3r, i think that ART does not support all features that SVG have.
see this dicussion: https://github.com/react-native-community/react-native-svg/issues/49

**Comment by a-r-d** [comment]
@normanrz I just published https://github.com/target/react-native-svg-parser which does what you are looking for

**Comment by sibelius** [comment]
You can try to use this one https://transform.now.sh/svg-to-react-native

**Comment by msand** [comment]
Docs have been updated: https://github.com/react-native-community/react-native-svg#use-with-svg-files
With react-native-svg-transformer you can now do this:
```jsx
import Logo from "./logo.svg";
const myApp = () => <Logo width={120} height={40} />
export default myApp
```

**Comment by msand** [comment]
You need to use react-native-svg-transformer, or something like babel-plugin-inline-import to ensure that code is bundled correctly:
https://github.com/react-native-community/react-native-svg#use-with-svg-files

**Comment by musadiq-jinbade** [comment]
#msand 
I ahve uses react-native-svg, react-native-svg-uri

**Comment by msand** [comment]
react-native-svg-uri requires using babel-plugin-inline-import to fix your issue

**Comment by musadiq-jinbade** [comment]
@msand , Okay I will try , Thanks for quickly updates

**Comment by musadiq-jinbade** [comment]
> react-native-svg-uri requires using babel-plugin-inline-import to fix your issue

I have to npm this babel-plugin-inline-import to fix this issue?

**Comment by msand** [comment]
Yes, and configure it: https://github.com/react-native-community/react-native-svg#use-with-svg-files

**Comment by musadiq-jinbade** [comment]
Okay, After installing react-native-svg-transformer and change some code in metro.config
I getting error :.
![Screenshot_2019-10-10-18-52-30-36_3c19b8dd7af3729c144d50503eacdc3e](https://user-images.githubusercontent.com/54430156/66572940-7e1a1500-eb8f-11e9-9d47-79455e4203f3.png)

**Comment by musadiq-jinbade** [comment]
can I know about in MainApplication importing:
package com.......;

import android.app.Application;
import android.util.Log;

import com.facebook.react.PackageList;
import com.facebook.hermes.reactexecutor.HermesExecutorFactory;
import com.facebook.react.bridge.JavaScriptExecutorFactory;
import com.facebook.react.ReactApplication;
import com.reactnativecommunity.asyncstorage.AsyncStoragePackage;
import org.reactnative.camera.RNCameraPackage;
// import com.horcrux.svg.SvgPackage;
import com.BV.LinearGradient.LinearGradientPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      // @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      packages.add(new LinearGradientPackage());
      // packages.add(new SvgPackage());
      return packages;
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}

**Comment by musadiq-jinbade** [comment]
> Okay, After installing react-native-svg-transformer and change some code in metro.config
> I getting error :.
> ![Screenshot_2019-10-10-18-52-30-36_3c19b8dd7af3729c144d50503eacdc3e](https://user-images.githubusercontent.com/54430156/66572940-7e1a1500-eb8f-11e9-9d47-79455e4203f3.png)

this issues is resolve by ->
change instead of source to svgXmlData, it should in string 

const svgImages =`<?xml version="1.0"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="512px" height="512px" class=""><g><g id="Storage"><rect x="5" y="41" width="18" height="20" style="fill:#ccb597" data-original="#CCB597"/><polygon points="16 47 16 41 14 41 12 41 12 47 16 47" style="fill:#ffaf46" data-original="#FFAF46"/><rect x="23" y="41" width="18" height="20" style="fill:#e5cbaa" data-original="#E5CBAA"/><polygon points="30 47 34 47 34 41 32 41 30 41 30 47" style="fill:#ffaf46" data-original="#FFAF46"/><rect x="41" y="41" width="18" height="20" style="fill:#ffe2bd" data-original="#FFE2BD" class=""/><polygon points="48 47 52 47 52 41 50 41 48 41 48 47" style="fill:#ffaf46" data-original="#FFAF46"/><rect x="14" y="21" width="18" height="20" style="fill:#ffe2bd" data-original="#FFE2BD" class=""/><polygon points="25 27 25 21 23 21 21 21 21 27 25 27" style="fill:#ffaf46" data-original="#FFAF46"/><rect x="32" y="21" width="18" height="20" style="fill:#ffe5c3" data-original="#FFE5C3"/><polygon points="39 27 43 27 43 21 41 21 39 21 39 27" style="fill:#ffaf46" data-original="#FFAF46"/><rect x="23" y="3" width="18" height="18" style="fill:#ffe5c3" data-original="#FFE5C3"/><rect x="30" y="3" width="4" height="4" style="fill:#ffaf46" data-original="#FFAF46"/><path d="M44,61H59V47C59,54.738,52.291,61,44,61Z" style="fill:#ffdaaa" data-original="#FFDAAA" class=""/><path d="M26,61H41V47C41,54.738,34.291,61,26,61Z" style="fill:#ceb799" data-original="#CEB799"/><path d="M8,61H23V47C23,54.738,16.291,61,8,61Z" style="fill:#b7a288" data-original="#B7A288"/><path d="M17,41H32V27C32,34.738,25.291,41,17,41Z" style="fill:#ffdaaa" data-original="#FFDAAA" class=""/><path d="M35,41H50V27C50,34.738,43.291,41,35,41Z" style="fill:#ffddb2" data-original="#FFDDB2"/><path d="M26,21H41V7C41,14.738,34.291,21,26,21Z" style="fill:#ffe1b9" data-original="#FFE1B9"/><path d="M10,57H8a1,1,0,0,0,0,2h2a1,1,0,0,0,0-2Z" data-original="#000000" class="active-path" style="fill:#000000"/><path d="M10,54H8a1,1,0,0,0,0,2h2a1,1,0,0,0,0-2Z" data-original="#000000" class="active-path" style="fill:#000000"/><path d="M28,57H26a1,1,0,0,0,0,2h2a1,1,0,0,0,0-2Z" data-original="#000000" class="active-path" style="fill:#000000"/><path d="M28,54H26a1,1,0,0,0,0,2h2a1,1,0,0,0,0-2Z" data-original="#000000" class="active-path" style="fill:#000000"/><path d="M46,57H44a1,1,0,0,0,0,2h2a1,1,0,0,0,0-2Z" data-original="#000000" class="active-path" style="fill:#000000"/><path d="M46,54H44a1,1,0,0,0,0,2h2a1,1,0,0,0,0-2Z" data-original="#000000" class="active-path" style="fill:#000000"/><path d="M59,40H51V21a1,1,0,0,0-1-1H42V3a1,1,0,0,0-1-1H23a1,1,0,0,0-1,1V20H14a1,1,0,0,0-1,1V40H5a1,1,0,0,0-1,1V61a1,1,0,0,0,1,1H59a1,1,0,0,0,1-1V41A1,1,0,0,0,59,40ZM49,42h2v4H49Zm0-2H33V22h5v5a1,1,0,0,0,1,1h4a1,1,0,0,0,1-1V22h5ZM31,42h2v4H31ZM42,22v4H40V22ZM33,4V6H31V4ZM24,4h5V7a1,1,0,0,0,1,1h4a1,1,0,0,0,1-1V4h5V20H24Zm0,18v4H22V22Zm-9,0h5v5a1,1,0,0,0,1,1h4a1,1,0,0,0,1-1V22h5V40H15Zm0,20v4H13V42ZM6,42h5v5a1,1,0,0,0,1,1h4a1,1,0,0,0,1-1V42h5V60H6Zm18,0h5v5a1,1,0,0,0,1,1h4a1,1,0,0,0,1-1V42h5V60H24ZM58,60H42V42h5v5a1,1,0,0,0,1,1h4a1,1,0,0,0,1-1V42h5Z" data-original="#000000" class="active-path" style="fill:#000000"/><path d="M17,39h2a1,1,0,0,0,0-2H17a1,1,0,0,0,0,2Z" data-original="#000000" class="active-path" style="fill:#000000"/><path d="M17,36h2a1,1,0,0,0,0-2H17a1,1,0,0,0,0,2Z" data-original="#000000" class="active-path" style="fill:#000000"/><path d="M37,37H35a1,1,0,0,0,0,2h2a1,1,0,0,0,0-2Z" data-original="#000000" class="active-path" style="fill:#000000"/><path d="M37,34H35a1,1,0,0,0,0,2h2a1,1,0,0,0,0-2Z" data-original="#000000" class="active-path" style="fill:#000000"/><path d="M26,16h2a1,1,0,0,0,0-2H26a1,1,0,0,0,0,2Z" data-original="#000000" class="active-path" style="fill:#000000"/><path d="M26,19h2a1,1,0,0,0,0-2H26a1,1,0,0,0,0,2Z" data-original="#000000" class="active-path" style="fill:#000000"/></g></g> </svg>`

<SvgUri width="38" height="27" svgXmlData={svgImages} />

**Comment by musadiq-jinbade** [comment]
<SvgUri width="38" height="27" svgXmlData={svgImages} />
