### ISSUE TITLE
Attempted import error: 'SvgXml' is not exported from 'react-native-svg'.

### ISSUE THREAD

**Issue by kopax** [react-native-community/react-native-svg#1236]
# Bug

I am not able to use `SvgXml`.

Since #1235 , I have a different import between web and native, I expected `SvgXml` to help me use svg on the web, using `babel-plugin-inline-svg`

## Environment info

- react-native-svg 9.13.3
- react-native-svg-transformer 0.14.3
- expo SDK: 36 Documentation: https://docs.expo.io/versions/latest/sdk/svg/

## Steps To Reproduce

```jsx
import { SvgXml } from 'react-native-svg';
import { Platform } from 'react-native-web';
import Logof from '../Logo';

const Logo = Platform.OS === 'web' ? <SvgXml xml={Logof} /> : <Logof />;
```

It should import the component

Instead, I have:

    Attempted import error: 'SvgXml' is not exported from 'react-native-svg'.

**Comment by kopax** [comment]
Apparently SvgXml does not exist for web and I was using wrong `import { Platform } from 'react-native-web'` instead of `import { Platform } from 'react-native'`

**Comment by msand** [comment]
I would recommend defining a separate Logo.js and either a Logo.web.js or Logo.native.js (or even Logo.ios.js and Logo.android.js) instead of using Platform. This way it only bundles the platform specific code (faster TTI), and essentially does the conditional logic at build time instead of repeatedly at run time (better performance).

**Comment by kopax** [comment]
Thanks for the recommendation, I am new in react-native ecosystem so I wouldn't have known. I will follow it
