### ISSUE TITLE
Using existing library to parse svg?

### ISSUE THREAD

**Issue by maxkomarychev** [react-native-community/react-native-svg#1277]
# Question

Hey!

I learned that implementation of `SvgUri` is using custom xml parser underneath.
I am wondering is there a reason (performance?) why some other battle-tested library was not used, e.g. https://www.npmjs.com/package/xmldom or https://www.npmjs.com/package/xml2js ?

Thanks :)

**Comment by msand** [comment]
Hey!

It is based on the excellent (and battle-tested) https://www.npmjs.com/package/svg-parser with a few modifications and optimisations. It got included while react-native-svg had zero run-time dependencies, and I wanted to keep it that way, until css support got included and the amount of work that would require to maintain properly. The svg parser is very simple, and the syntax is very unlikely to change, and svg-parser was very close to what I wanted in this case. As this library is used in relatively performance critical parts, I wanted to tailor make the implementation for the specific use-case, rather than wait for PRs to be merged/rejected.

**Comment by msand** [comment]
Also, svg-parser had the best performance of all the parsers I tested.

**Comment by maxkomarychev** [comment]
uh, perhaps I missed reference to `svg-parser` :)
works for me, thanks!
