### ISSUE TITLE
tvOS / Apple TV Support

### ISSUE THREAD

**Issue by alexthegoodman** [react-native-community/react-native-svg#304]
Are there any plans to create a tvOS implementation? RN supports this officially now, but it doesn't seem to integrate as-is.

**Comment by redpandatronicsuk** [comment]
I'm using it in an app that's already available on the AppStore for tvOS (https://itunes.apple.com/us/app/my-trump/id1212604425), which uses react-native-svg.
To make it work on tvOS, you need to select RNSVG.xcodeproj in the Libraries folder in the left side panel, then Bild Settings and then in supported platform, select tvOS.
I have to change back and forth between iOS and tvOS when building for the different platforms, maybe there is a way to say it supports both platforms, so it doesn't need to be changed every time I need to make an updated build?
<img width="1133" alt="screen shot 2017-04-11 at 14 07 25" src="https://cloud.githubusercontent.com/assets/8609582/24910843/f972dbd6-1ec0-11e7-9240-d06bab130c2a.png">

Extra tip: My app got rejected the first timeI submitted to the AppStore, because on the home screen, the Menu button on the Siri remote is supposed to exit the app. In RN 0.42, I found no built-in way to doing this, but found a solution, I wrote about here: http://stackoverflow.com/questions/43047256/exit-react-native-tvos-app-programetically

**Comment by alexthegoodman** [comment]
@redpandatronicsuk You, my friend, are fantastic. Should've thought of that myself! Thank you

**Comment by magicismight** [comment]
#319 has landed on 5.1.8
