### ISSUE TITLE
Requesting a simple way to vertically align text in a container

### ISSUE THREAD

**Issue by ndbroadbent** [react-native-community/react-native-svg#308]
Right now I can't figure out how to do this without manually setting `dy`. I'm using `textAnchor="middle"` to center the text horizontally, but I have to set `y={HEIGHT / 2}`, which vertically centers the top of the Text element. So then I have to manually figure out the height and set a `dy` value to `textHeight / -2`, so that the Text is vertically centered.

It would be nice if I could change the "origin" of the text to be in the center of the Text element. Or if there could just be a "vertical alignment" option. Or if I could just force a "line height" for the Text, so that I can be confident in the `dy` setting. Because right now I have to set two different `dy` values for iOS and Android, because they seem to render differently.

Thanks!

**Comment by ndbroadbent** [comment]
I've just figured out how to properly center vertically on both iOS and Android. Apparently the magic number is: `0.25 * fontSize`.

```
const fontSize = 64;
const width = 200;
const height = 200;

<Text
  fill="white"
  fontFamily="Helvetica"
  fontWeight="bold"
  fontSize={fontSize}
  textAnchor="middle"
  x={width / 2}
  y={(height / 2) - (fontSize / 2)}
  height={fontSize}
  dy={fontSize * -0.25}
>
  hello
</Text>
```

Here it is with a red fill + blue rect to show `fontSize`:

### Android:

<img width="174" alt="screenshot 2017-04-16 14 52 25" src="https://cloud.githubusercontent.com/assets/139536/25069754/d6507e68-22b4-11e7-853a-b78cdc1d6901.png">

### iOS:

<img width="148" alt="screenshot 2017-04-16 14 52 45" src="https://cloud.githubusercontent.com/assets/139536/25069755/dca18f96-22b4-11e7-8e34-30b3662977e9.png">


Is there a nicer way to do this?

**Comment by msand** [comment]
In the latest versions this should be working in a spec conformant way in both android and ios. Please re-open if not.

**Comment by hpdeveloper28** [comment]
You can add following style for Vertically center Text.

`childTextLeft: {
        flex: 1,
        fontSize: 20,
        color: 'white',
        fontStyle: 'italic',
        fontWeight: 'bold',
        textAlign: "left",
        textAlignVertical: "center"
    },`

**Comment by sunilkumarc** [comment]
`textAlignVertical: 'center'` did the trick for me!

**Comment by jaideeprawat** [comment]
÷÷Happy coding
<ImageBackground source={require('..imagepath')} style={{width: '100%', height: '100%'}}>
          <View style={{position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, justifyContent: 'center', alignItems: 'center'}}>
         <Text>Centered text</Text>
         </View>
      </ImageBackground>

**Comment by quantumpotato** [comment]
textAlignVertical: 'center' did not work for me 
using a TouchableOpacity wrapped around the Text

**Comment by DarkKnight1992** [comment]
i am having a issue regarding vertical bottom alignment which should not be a issue generally i  guess not sure if its the expected behaviour. There the issue 

![image](https://user-images.githubusercontent.com/15063261/67280359-9de3fe00-f4ea-11e9-99ad-34bae6ea4d9d.png)

since bottom text have a huge difference in height aligning them to the bottom is really not optimal.

i have tried changing the line height as well but than the test cuts off at the top

![image](https://user-images.githubusercontent.com/15063261/67280485-e7cce400-f4ea-11e9-86cc-febd422c81ad.png)

the lineHeight is exactly same as the fontSize not really sure but i not able to get rid of the space at the bottom of text, .i.e there is no padding or margin at the bottom it just stays like that again not sure why is that.

i am new to react native - not sure if this a bug or the expected behaviour.

If someone can help me understand this that would be great.

i thank you for taking for time to explain this, in advance.
