### ISSUE TITLE
Rotate is not working after update

### ISSUE THREAD

**Issue by sms1989** [react-native-community/react-native-svg#475]
After Update Rotate props not working in react-native-svg

"react": "16.0.0-beta.5",
"react-native": "0.49.1",
"react-native-svg": "^6.0.0-rc1",

**Comment by sms1989** [comment]
Rotate props change to "rotation" in "react-native-svg": "^6.0.0-rc1" BUT IT'S NOT DOCUMENTED

**Comment by msand** [comment]
Sorry for this, my fault. I changed it because the rotate attribute in text elements like e.g. tspan was applied both to the glyph and the entire element. Other svg elements shouldn't interpret the rotate attribute (although react-native-svg allows transform definitions as attributes, which is not part of the svg spec). At the same time I had removed support for rotate transform definitions in the transform attribute by mistake. If you change:
https://github.com/react-native-community/react-native-svg/blob/6.0.0/lib/extract/extractTransform.js#L139
from:
`rotation: +props.rotation || 0,`
to:
`rotation: +props.rotation || +props.rotate || 0,`
then it should work again. 

To conform with the spec, we should remove support for transform definitions as straight attributes, and remove support for the "rotation" definition, only keeping the transform definition form of rotate.

**Comment by msand** [comment]
Also the optional parameters of rotate aren't supported, and there is support for some attributes/definitions which aren't in line with spec: skew, translateX, translateY, origin, originx, originy, scalex, scaley. And value separation using whitespace (comma-wsp) is not supported causing incorrect handling of e.g. two parameter scale definitions without commas to separate them, etc.

**Comment by sms1989** [comment]
@msand  
Thanks for your responding
**Please documenting this for other user ....**

**Comment by msand** [comment]
Full rotate is supported as a transform definition in the transform attribute now. Closing.
