### ISSUE TITLE
No documentation for rotate

### ISSUE THREAD

**Issue by nating** [react-native-community/react-native-svg#565]
It seems that the rotate transform [was implemented](https://github.com/react-native-community/react-native-svg/pull/507) but it isn't very clear at all how to get it to work. It seems that at different stages of development it could have been used differently:

```jsx
<Rect x={0} y={0} width={10} height={10}  rotate="45, 5, 5" />
```
or  
```jsx
<Rect x={0} y={0} width={10} height={10} transform={{ rotate: '45, 5, 5' }} />
```
or possibly something like:  
```jsx
<Rect x={0} y={0} width={10} height={10} transform="rotate(45, 5, 5)" />
```

I can't get rotation to work with any of these syntaxes. I have reviewed [the parser](https://github.com/react-native-community/react-native-svg/blob/master/lib/extract/extractTransform.js) but it's not really clear how to use the rotation correctly! 😅

**Comment by msageryd** [comment]
I just struggled with this and found a comment about this from @msand. In #475.

Easiest workaround for now is to use "rotation" instead of "rotate. Also, there is no support for the x and y parameters, but I thik you can use originX and originY instead.

`transform={{ rotation: 45, originX: 5, originY: 5 }}`

**Comment by msand** [comment]
@nating @msageryd The [standard syntax](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform) is supported in the latest versions, since https://github.com/react-native-community/react-native-svg/pull/507 was merged. The non-standard attribute and transform object requires using the rotation property name rather than rotate, not to collide with the standards conformant rotate attribute on text elements.
An example of the standard [transform attribute](https://www.w3.org/TR/SVG/coords.html#TransformAttribute) can be seen here: https://github.com/msand/SVGPodTest/commit/49c97ab48b7ada3e634d73175f792ac331a39579#diff-958f6f56cd42c904603d226cd36a57b6R39

```jsx
<Rect
  x="0"
  y="0"
  width="65"
  height="65"
  fill="white"
  transform="rotate(45, 32.5, 32.5)"
/>
```
And some examples from the spec can be seen here: https://github.com/msand/react-native-svg-example/blob/SpecTests/src/components/Nested.js#L23
https://github.com/msand/react-native-svg-example/blob/SpecTests/src/components/RotateScale.js#L16

**Comment by msageryd** [comment]
Great, thanks.
Is the support for rotation center new, or did I just miss it before?

**Comment by msand** [comment]
It came with https://github.com/react-native-community/react-native-svg/pull/507 so its relatively new. The transform parser isn't available in Expo for example..
