### ISSUE TITLE
Support for Web

### ISSUE THREAD

**Issue by necolas** [react-native-community/react-native-svg#608]
I get bug reports from people using this library and trying to run their apps on the web using React Native for Web.

Web support could be added by exporting the SVG components from React DOM or wrapping them in React Native for Web's `createElement`. And compiling the package before publishing to npm. It may be complicated by the decision to deviate from the SVG standard and add things like `setNativeProps` to the native components.

Here's an example of how much massaging needs to be done to convert this library's API to the SVG standard on web https://github.com/godaddy/svgs/blob/master/index.js

**Comment by necolas** [comment]
Previous issue was closed without resolution https://github.com/react-native-community/react-native-svg/issues/155

**Comment by msand** [comment]
Hmm, is https://github.com/godaddy/svgs insufficient?

**Comment by necolas** [comment]
Why not do that work here? And even align the native API with the web?

**Comment by msand** [comment]
Sure, sounds like a good idea actually. Would you have any time for this?
The main difference would probably be that quite a few things from the spec are still lacking support, compared to the ever-green browsers.
Also, the APIs could probably be generated from the WebIDLs, to get the getters, setters and methods exposed as well. Enabling use of the existing unit test suites.

**Comment by msand** [comment]
@3rd-Eden What do you think? How much work would it be to integrate svgs into react-native-svg? And make it work seamlessly with react-native-web?

**Comment by necolas** [comment]
What kind of things are missing relative to browsers?

**Comment by msand** [comment]
The readme has a small (incomplete) summary at the end https://github.com/react-native-community/react-native-svg#todo 
Also, filters aren't supported (blend, convolutions, offset copies, composites, lighting, blur, shadows etc), the animated element, and animated attributes, color-profiles, css and style elements, 3d transforms, text layout has some bugs, vertical and rtl text isn't properly supported, defining svg fonts, foreign-object (web-view). But most of all, all the DOM interfaces and events are missing. And surely I'm forgetting some things still which people take for granted in the web.

**Comment by indexzero** [comment]
> Just my $0.02. I'm sure @3rd-Eden has feels as well.

Cross-platform feature parity aside, the bulk of the work that `svgs` does is transform certain `react-native-svg` props into `transform`. See [`prepare` in `svgs`](https://github.com/godaddy/svgs/blob/master/index.js#L31-L88).

From a conceptual perspective thought won't that work cease to make this library `react-native-svg`? Since it will work with web & native? It would just be `svgs`, just not a wrapper to anything.

**Comment by necolas** [comment]
For my needs/interests (multi-platform icon components from SVG) the only thing missing was support for React Native's `style` prop on `Svg`. If that's possible and is introduced for native, you'd need `react-native-web` for the web version (`const Svg = () => ReactNativeWeb.createElement('svg', props)`). I think full parity with the DOM is less interesting that carving out an effective subset that works across platforms (following React Native's philosophy.)

**Comment by msand** [comment]
@indexzero Sure, make sense, had some similar thoughts last summer when I started maintaining this and using svgs.
@necolas What parts of the style props would you need which aren't already supported by some similar part of the svg spec? At least css can be preprocessed and inlined as element attributes as long as the svg only has static styles. Paths, colors and transforms can be changed already, and are inherited by ancestors of G elements, what more do you need for icons?

**Comment by necolas** [comment]
Basically what's used here: http://nicolasgallagher.com/making-svg-icon-libraries-for-react-apps/

**Comment by msand** [comment]
```
const styles = StyleSheet.create({
  root: {
    display: 'inline-block', // This is default in RN no?
    fill: 'currentcolor', // If you wrap your content in a G element, you can set fill for all ancestors to inherit it
    height: '1.25em', // RN doesn't support em in sizing their elements, can use pixels instead (and soon percentages in the root svg element of rnsvg as well)
    maxWidth: '100%', // RN already support this on the root svg element no?
    position: 'relative', // This is default for RN right?
    userSelect: 'none', // Nothing is selectable by default in RN anyway, or?
    textAlignVertical: 'text-bottom' // (rn)svg supports the alignmentbaseline and vertical align attributes
  }
});
```
I think your use case can be covered with an already existing subset of the web and react-native(-svg), am I missing something?

**Comment by necolas** [comment]
Maybe? I didn't see anything in the docs about support for the style prop

**Comment by geminiyellow** [comment]
try to use `react-native-svg` with `react-native-web`, but 
the `createReactNativeComponentClass` use `__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED` in `ReactNative`.
cannot import module correctly.

**Comment by necolas** [comment]
There's also a bad Touchable import https://github.com/necolas/react-native-web/issues/833#issuecomment-367576040

**Comment by 3rd-Eden** [comment]
@msand Apologies for the delayed response, work & life happened. While it's definitely possible to integrate the work that `svgs` did in to `react-native-svg` I don't know if that makes sense here. As @indexzero said that would no longer make this a `native` library. It's a library that works on all platforms.
	
Originally I started working `svgs` to create a library that allowed us to components that are completely isomorphic and work on React and React-Native without any requirements on libraries or build chains. E.g react-native-web and webpack aliases. This is so any developer and in our case, any team could leverage this library. This is why I decided to with an `index.js` and an `index.native.js` so I could explicitly target various of platforms from a single code base.
	
While I applaud @necolas for his efforts in react-native-web it was not a design pattern that we wanted to adopt. So we went with `svgs` instead of calling this `react-native-svg-web` because it works without `react-native-web` and the webpack toolchain (it still works fine with react-native-web through webpack aliasing as documented in the [svgs README](https://github.com/godaddy/svgs)).
	
As for making isomorphic icon libraries, we also did that for GoDaddy using svgs, but instead of using `style` we supply the color changes directly to the `<G>` component as `fill` attribute. So we ended up with:
	
```js
<Icon name='magic' color="red" size={10} />
```

**Comment by msand** [comment]
I've forked svgs to support react-native-web and published it under the name swgs to see how much interest there is for this
https://www.npmjs.com/package/swgs
Essentially the only difference so far is to use 
`import { createElement } from 'react-native-web';`
 instead of 
`import React from 'react';`
https://github.com/msand/swgs/commit/d5ac0a4e93e6bad3b8ed190c6833adf58361fcfc#diff-168726dbe96b3ce427e7fedce31bb0bcR1
@necolas Are there any more changes needed on the native side or in swgs at this point?

**Comment by msand** [comment]
Example:
```jsx
import { Svg, Path } from 'swgs';

export default props => (
  (
    <Svg
      title="pencil"
      x="0px"
      y="0px"
      width="20px"
      height="20px"
      color="white"
      style={{ margin: 5 }}
      viewBox="0 0 512 512"
      {...props}
    >
      <Path
        fill="currentColor"
        d="M318.37,85.45L422.53,190.11,158.89,455,54.79,350.38ZM501.56,60.2L455.11,13.53a45.93,45.93,0,0,0-65.11,0L345.51,58.24,449.66,162.9l51.9-52.15A35.8,35.8,0,0,0,501.56,60.2ZM0.29,497.49a11.88,11.88,0,0,0,14.34,14.17l116.06-28.28L26.59,378.72Z"
      />
    </Svg>
  )
);

```

**Comment by 3rd-Eden** [comment]
Because you can probably feature detect `react-native-web` usage, and fallback to `createElement` from `react` if `react-native-web` is not in the node_modules tree.

**Comment by msand** [comment]
Now I have this kind of Icons working cross-platform:
```jsx
import React from 'react';
import { Svg, Path } from 'swgs';

export default props => (
  <Svg
    title="pencil"
    x="0"
    y="0"
    width="20"
    height="20"
    color="green"
    style={{ margin: 5 }}
    viewBox="0 0 512 512"
    {...props}
  >
    <Path
      fill="currentColor"
      d="M318.37,85.45L422.53,190.11,158.89,455,54.79,350.38ZM501.56,60.2L455.11,13.53a45.93,45.93,0,0,0-65.11,0L345.51,58.24,449.66,162.9l51.9-52.15A35.8,35.8,0,0,0,501.56,60.2ZM0.29,497.49a11.88,11.88,0,0,0,14.34,14.17l116.06-28.28L26.59,378.72Z"
    />
  </Svg>
);

```

**Comment by msand** [comment]
The width and height attributes also work with percentages, I think the svg logic should also work with em but it would fall back to 12px as the user-agent default so can just as well multiply by 12, and I think RN/Yoga would choke on it anyway. And the fact that View elements don't have font size and that it can't be nested inside of Text elements at the moment, make font-size relative svg bitmap sizes a bit redundant.

**Comment by msand** [comment]
I'm not sure if the RN team is interested in adding support for the color attribute to the View element, it should probably stay layout focused. If someone would look at supporting Svg inside Text, then we could look at inheriting the font color as well as font-size relative size. But, as a tradeoff for now, I think having a color attribute on the Svg element gives a nice way to set one color across all the content in a tree, and which is easy to override with a property, and G elements + stroke & fill inheritance can be used for more selective color re-use.

**Comment by msand** [comment]
Added support for the fill and stroke attributes on the Svg root element now. Allowing to set a default stroke, and fill, plus a third color attribute, which can be used as currentColor in any color accepting attribute, without having to create a nesting G element.

**Comment by msand** [comment]
i've added basic support for the style attribute now. @necolas Do you have any example which isn't working the same in native as in web? Would be great to have some examples of (preferably troublesome but spec conformant) content using RNW styles.

**Comment by 3rd-Eden** [comment]
@msand Shouldn't support for both would be as easy as adding:

```js
try { createElement = require('react-native-web').createElement; }
catch (e) {
  createElement = require('react').createElement;
}
```

So when people don't have `react-native-web` installed, it will default to react's `createElement`

**Comment by necolas** [comment]
> Do you have any example which isn't working the same in native as in web?

For `react-native-svg`?

**Comment by msand** [comment]
Now with support for setting dimensions using Stylesheet / style attribute.
![screen shot 2018-10-05 at 3 55 21](https://user-images.githubusercontent.com/1131362/46510590-9d7eb380-c852-11e8-9a13-426bfa07caf5.png)
```jsx
import React, { Component } from 'react';
import { StyleSheet, View } from 'react-native';
import { Svg, Path, Rect } from 'swgs';

const Pencil = props => (
  <Svg
    title="pencil"
    style={{
      width: '100%',
      height: '100%',
      color: 'green',
      fill: 'currentColor',
    }}
    viewBox="0 0 512 512"
    preserveAspectRatio="xMidYMid meet"
    {...props}
  >
    <Rect
      x="0"
      y="0"
      width="512"
      height="512"
      stroke="blue"
      fill="#E5ECEF"
      strokeWidth="4"
    />
    <Path d="M318.37,85.45L422.53,190.11,158.89,455,54.79,350.38Z
             M501.56,60.2L455.11,13.53a45.93,45.93,0,0,0-65.11,0
             L345.51,58.24,449.66,162.9l51.9-52.15A35.8,35.8,0,0,0,501.56,60.2Z
             M0.29,497.49a11.88,11.88,0,0,0,14.34,14.17l116.06-28.28L26.59,378.72Z"
    />
  </Svg>
);

export default class App extends Component {
  render() {
    return (
      <View style={[StyleSheet.absoluteFill, styles.container]}>
        <View style={styles.img}>
          <Pencil />
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#F5FCFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  img: {
    backgroundColor: '#F5FCFF',
    borderColor: 'black',
    borderWidth: 2,
    height: '50%',
    width: '50%',
  },
});

```

**Comment by msand** [comment]
@necolas Yes, if you happen to know of any content which doesn't work satisfactorily yet. Or, can think of any attributes/properties/styles which you still might wan't support for.

**Comment by msand** [comment]
@3rd-Eden Hmm, yeah I guess that should actually work.

**Comment by carlost** [comment]
> Or, can think of any attributes/properties/styles which you still might wan't support for.

sorry if I am late to the party @msand or if this is out of scope, but touch support is missing from `svgs`.  We use `react-native-web` with a webpack alias to replace `react-native-svg` with `svgs`.  We have issues with a 3rd party lib, `react-native-svg-charts`, that is passing `onPress` handlers to various `react-native-svg` components.  `svgs` doesn't have any special touch handling support, so that prop is passed as is to the svg DOM element it creates.  needless to say, touch all you want ... the onPress handler isn't going to be triggered.

It would be great if `svgs`, or whatever ends up offering cross platform svgs, could leverage all of the work already done in `react-native-web` to handle touch/click events (`TouchableMixin` etc).

**Comment by necolas** [comment]
I'm not sure it's a good idea to have `onPress` on SVGs, unless the touchable functionality is mixed in only when an `onPress` function is provided (as `Text` does). There are existing components that can wrap SVGs to provide this functionality (and all the other press-related functionality) without folding it into an SVG component. The main problem with `svgs` is the API is not compatible with React Native more generally, e.g., `style`

**Comment by rpweb** [comment]
thanks guys, works perfectly

**Comment by rpweb** [comment]
Thanks guys, works perfectly for me.
