### ISSUE TITLE
react-native-svg:verifyReleaseResources'

### ISSUE THREAD

**Issue by yazpid** [react-native-community/react-native-svg#669]
When I'm try genreated APK my app, I'm have a error like below (I use `gradlew assembleRelease)`: 
`Execution failed for task ':react-native-svg:verifyReleaseResources'.
 com.android.ide.common.process.ProcessException: Failed to execute aapt`

`gradlew assembleDebug` works corectly, can you give any information what is wrong ?

**Comment by andyrewlee** [comment]
I was getting this error using 6.1.x. The error went away after upgrading to 6.5.2.

**Comment by laibulle** [comment]
Same problem with version `^7.0.3`. Switching to `6.5.2` resolved the problem.

**Comment by msand** [comment]
Can you try with the latest version? I suspect it's something with your android / gradle setup, check here eg: https://github.com/evollu/react-native-fcm/issues/800
https://github.com/facebook/react-native/issues/19239
https://github.com/rebeccahughes/react-native-device-info/issues/365#issuecomment-425662649
Otherwise, please try to replicate it in a clean project which can be cloned and tested easily.

**Comment by msand** [comment]
Please provide a full replication. Closing until then.
