### ISSUE TITLE
Can't use setNativeProps to set rotation on Svg.G

### ISSUE THREAD

**Issue by designingSparks** [react-native-community/react-native-svg#712]
I'm using Animate to try and transform Svg elements in this library as follows:

addListener to the Animated value.
Call setNativeProps to directly update the parameter to update the parameter:

```
this.state.animator.addListener( ({value}) => {
       this._animG.setNativeProps({rotation: value.toString()});
});
```
This is very similar to the approach [here](https://github.com/react-native-community/react-native-svg/issues/438). This doesn't work for the rotation property on the Svg.G element. However, this works with properties on other elements.

What could be the problem?
What is the quickest way to discover the native properties of an element?

**Comment by kozilla** [comment]
@designingSparks , I am falling into the same problem. After digging a bit I have found out that instead using rotation (which turned out not be on the list of the nativeProps for G) , you can use nativeProps  called matrix. Using it you can perform all anim effects directly through matrix transformation (translation , rotation , scale).
more info : https://stackoverflow.com/questions/47981530/transform-g-with-setnativeprops-possible-with-react-native-svg

also if you are wondering what native props exist for G , you can see all list under ref :
root.viewConfig.NativeProps

**Comment by msand** [comment]
You can also use react-native style transforms to do animated rotations. Closing now.
