### ISSUE TITLE
<G translate='x, y'> is no longer working since @6.x.x

### ISSUE THREAD

**Issue by 3rd-Eden** [react-native-community/react-native-svg#717]
As per title, it seems this functionality got broken with the recent refactor of the transform handling in React-Native-SVG. In version 5.5.1 this is working as intended:

```js
const translate = [160, 80];

<Svg width={ props.width } height={ props.height }>
  <G translate={ translate.join(', ') }>
    { dots }
  </G>
</Svg>
```

But it fails in any build of `@6.x.x` release that are out. I did manage find a workaround for those who run into the same issue and that is use to `x` and `y` instead of `translate`: 

```js
const translate = [160, 80];

<Svg width={ props.width } height={ props.height }>
  <G x={ translate[0] } y={ translate[1] }>
    { dots }
  </G>
</Svg>
```

**Comment by msand** [comment]
I would recommend using the standard transform attribute with the translate transform definition https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Basic_Transformations#Translation 
https://www.w3.org/TR/SVG11/coords.html#TransformAttribute
instead of the non-standard x and y attributes. As in: 
```jsx
const translate = [160, 80];

<Svg width={ props.width } height={ props.height }>
  <G transform={`translate(${translate[0]},${translate[1]}`}>
    { dots }
  </G>
</Svg>
```
