### ISSUE TITLE
React/React Native compatibility

### ISSUE THREAD

**Issue by evert-smit** [react-native-community/react-native-svg#747]
Hi,

The notice in README.md clearly says: react-native-svg >= 5.5.1 only supports react-native >= 0.50.0 and react == 16.0.0.

1. What's the reason for the incompatibility between react-native-svg and various react/react-native versions?
2. What's the approach for dealing with it?
3. What's the general timeline/goal for adding support for newer react/react-native versions?

Could someone shed some light on this?

Thanks!

**Comment by msand** [comment]
The latest version should be working fine with the latest react-native version. Or at least, running react-native init, npm i react-native-svg, and, react-native link, should work with minimal fuzz; to be as newcomer friendly as possible. 

The version incompatibilities are only related to breaking changes in react-native, if you get it to build, then it is probably working to its full extent. Please feel free to try linking and building any pair of versions you need, and otherwise attempt to use the latest of both.

There hasn't been many major breaking changes since 0.50 with regards to the apis used by react-native-svg, so no new entries have been added to the version (in)compatibility table.

**Comment by evert-smit** [comment]
That clarifies it, thanks for explaining! Much appreciated! :)

**Comment by evert-smit** [comment]
Interesting. Seems like a good idea to stick to that recommended version
then. Thanks for the hint.
