### ISSUE TITLE
Extract color at any LinearGradient position [Feature question]

### ISSUE THREAD

**Issue by alexsmartens** [react-native-community/react-native-svg#838]
I am using gradient for giving visual representation to a current value on a scale, where green means that the value is inside acceptable limits and red means that the value is outside of those limits. The scale showing these limits is implemented with `LinearGradient` and `Path`, the value marker is implemented with `Path` and the value itself is implemented with RN `Text`. 

The question is 
### given the current value, how to extract the color corresponding to it in the `LinearGradient`, so that I can use this color to fill the value marker and the value text?

Here is an example of how my screen looks now and how I want it to look like:

![image](https://user-images.githubusercontent.com/26261714/48104307-ed112000-e200-11e8-9aff-6aa5fbcf3b40.png)

Here is my code:

```
<View>
  {/* Speed Sensor */}
  <Text style={[styles.sensorNameText]}>Speed</Text>
  {/* Current sensor value */}
  <Text style={[styles.sensorValueText, {color: "green"}]}>{this.state.speedValue}kmh</Text>

  <Svg height={this.state.widthViewLevel2} width={this.state.widthViewLevel2}>
    {/* Creating gradient color fill */}
    <Defs>
      <LinearGradient id="gradient2" x1="0%" y1="0%" x2="100%" y2="0%">
        <Stop offset="0" stopColor="red"/>
        <Stop offset="0.5" stopColor="green"/>
        <Stop offset="1" stopColor="red"/>
      </LinearGradient>
    </Defs>
    {/* Color scale */}             
    <Path
      d={"M10 20 L " + (this.state.widthViewLevel2-10).toString() + " 20"}
      fill="none"
      stroke="url(#gradient2)"
      strokeWidth="15"
    />
    {/* Number Scale */}
    <TextSvg
      fill="black"
      fontSize="17"
      x="15"
      y="47"
      textAnchor="middle"
    >0</TextSvg>
    <TextSvg
      fill="black"
      fontSize="17"
      x="105"
      y="47"
      textAnchor="middle"
    >100</TextSvg>
    {/* Current sensor value marker */}
    <Path
      d={"M" + this.state.speedValue + " 8 L " + this.state.speedValue + " 32"}
      fill="none"
      stroke="black"
      strokeWidth="1.5"
    />
  </Svg>
</View>
```
Any idea how to do it?

**Comment by alexsmartens** [comment]
Hi, can anyone help with this?

@msand, I've noticed you answered many questions of similar type. Could you suggest something in this case?

**Comment by msand** [comment]
@alexsmartens Hey there, the colors are interpolated linearly, inside any part of the gradient it is normal arithmetic where you have an input parameter x giving an argument in [0, 1] with two constants a and b, and the result is (1-x)*a + x*b 

But, the colors have several color components, so you'll probably want to use something from npm like: 
```js
const interpolate = require('color-interpolate');

let colormap = interpolate(['red', 'green', 'red']);
let redleft = colormap(0); // 'rgb(255, 0, 0)'
let inbetween = colormap(.25); // 'rgb(128, 128, 0)'
let green = colormap(.5); // 'rgb(0, 255, 0)'
let redright = colormap(1); // 'rgb(255, 0, 0)'

let colorAnywhereElse = normalizedDistanceAlongAxis => colormap(normalizedDistanceAlongAxis);
```
Then just calculate how far along your scale you are as a number and call that function. color-interpolate does clamping for you, i.e. ensuring you stay inside the scale instead of doing extrapolation. So, it does everything you need except the part which is specific for your app: deciding the scale and colors, and mapping touch events back to the scale.
So, no need to use the native layer for this, you have all the information you need to calculate this already and going over the bridge would just make things slower.

**Comment by alexsmartens** [comment]
Thanks for your suggestions @msand! I solved the problem by computing RGB color values in my function
