### ISSUE TITLE
[Android] Project Integration Should Use Normal Gradle Dependencies

### ISSUE THREAD

**Issue by wokkaflokka** [react-native-community/react-native-svg#858]
According to the README, the way to integrate this project for Android is to define a target in `settings.gradle` that links to the underlying source in the `node_modules`. While this approach works, there are alternatives that may prove simpler and more canonical. In my opinion, the ideal integration for this project would follow the pattern set forth by `react-native`, allowing Android projects to add a Gradle dependency on the relevant source packaged via NPM. Something like:

```
...
dependencies {
   ...
   implementation "com.horcrux.svg:react-native-svg:+"
   ...
}
...
```

Also of note, the process of defining a module and creating cross-references to it can be more succinctly accomplished as follows:

```
android {
    ...
    sourceSets.main.java.srcDirs += ["${project.rootDir}/node_modules/react-native-svg/android/src/main/java"]
    ...
}
```

If there is consensus that a better integration point for Android can be achieved, I would be happy to lead up the contribution.

Thanks,
Emery Coxe

**Comment by msand** [comment]
If you can make a PR and show an example of how this simplifies things then we can surely consider it. Are there any other react-native modules using this pattern?

**Comment by Legend1991** [comment]
@msand Hi
`dependencies {
        //noinspection GradleDependency
        classpath 'com.android.tools.build:gradle:3.2.1'
 }`
updating to 3.2.1 version will fix the issue

**Comment by wokkaflokka** [comment]
@msand I'll look into. `react-native` itself is using this pattern: https://facebook.github.io/react-native/docs/integration-with-existing-apps#configuring-maven

**Comment by msand** [comment]
Yes, but react-native has a bunch of c/c++ code which would require installing the ndk, and a 20minute build just to get started otherwise. Building this library tends to take a few seconds. So I'm not sure it's worth the hassle. I haven't seen it done by any other module. But please do make the change so we can measure and compare.

**Comment by msand** [comment]
I guess this can be closed. Or are you still looking into this? @wokkaflokka

**Comment by wokkaflokka** [comment]
@msand thanks for following up. I haven't really looked into this until briefly this morning. While I agree with some of your points about why the `react-native` uses this approach when others do not, additional motives that could inform why Facebook uses this approach include:

1. Distributing as a pre-compiled AAR treats the Android code more like an artifact dependency rather than a source dependency.
2. Under the current integration point of `react-native-svg`, it is possible to change the source code (though certainly not advised) under the `node_modules` path. When the android source is distributed as an AAR, this is much more difficult to do, for better or worse. I think for the case of `react-native` this would encourage issues to be raised against the project rather than worked around locally.

Digging into the `react-native` codebase, they achieve this behavior by [configuring their build to compile the Android source](https://github.com/facebook/react-native/blob/master/ReactAndroid/release.gradle), outputting the resultant aar in a folder local to the packaged npm artifact.

<img width="509" alt="screen shot 2019-02-15 at 10 58 03" src="https://user-images.githubusercontent.com/995007/52871864-a50f6c80-3110-11e9-8a5d-1b82af5bb4ad.png">

After starting down this route, I elected to stop. I think for this project, the cost of this change might outweigh the benefit under the existing circumstances.

I will note, the projects we have using `react-native-svg` still integrate the source in a manner different than that prescribed by this project's README. Specifically, we add the source as I documented in my first comment:

```
android {
    ...
    sourceSets.main.java.srcDirs += ["${project.rootDir}/node_modules/react-native-svg/android/src/main/java"]
    ...
}
```

Thanks for your diligence and for maintaining this project.

**Comment by msand** [comment]
@wokkaflokka Interesting, thanks for looking into it! I think in our case, it might actually be helpful that people can merely change the source in node_modules in attempts to find fixes to issues, rebuild, verify and open a pr.
With regards to the source set, I think that is decided by https://github.com/react-native-community/react-native-cli 
I'm not sure what are all the effects your suggested changes would have, could you explain what are the differences?

**Comment by ltegman** [comment]
@msand I can't speak to what @wokkaflokka was using sourceSets for, but at my company this is a desirable alternative to adding a project in `settings.gradle` because we're working within a large existing android codebase where the workflow is gradle based. Following the usual method of adding a project to `settings.gradle` causes the build to fail if developers don't run a `yarn install` before the gradle build, which adds friction to an android developer's workflow. By following this alternative method we can have a subproject run a `yarn install` from within gradle and keep the build entirely gradle based.

Anyways, thanks for this module and thanks @wokkaflokka for the solution to the gradle issue we were having!

**Comment by msand** [comment]
@ltegman Interesting, are you saying you have gradle task running `yarn install` as a command-line, to avoid having android developers run an additional command? I guess this applies even in a plain react-native project without any extra modules then? Or how would you have anything in node_modules otherwise?
